# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SinCode < Formula
  desc "SIN-Code unified toolchain — 90+ subcommands and 52+ MCP tools in one static binary"
  homepage "https://github.com/OpenSIN-Code/SIN-Code"
  version "3.26.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/OpenSIN-Code/SIN-Code/releases/download/v3.26.0/sin-code_3.26.0_darwin_amd64.tar.gz"
      sha256 "0d5aef0fcdf85828ad9205ca20035a2de790fa11265bda71165e19dff59c7236"

      define_method(:install) do
        bin.install "sin-code"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/OpenSIN-Code/SIN-Code/releases/download/v3.26.0/sin-code_3.26.0_darwin_arm64.tar.gz"
      sha256 "bdfc5191fe4b40015068dddbcb71b019f59213a5c7ac534464141cbe001fcaae"

      define_method(:install) do
        bin.install "sin-code"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/OpenSIN-Code/SIN-Code/releases/download/v3.26.0/sin-code_3.26.0_linux_amd64.tar.gz"
      sha256 "719ffe07f5806aa980a2d9a4ac4b03221f40430ce0912b95a7646477d7183569"
      define_method(:install) do
        bin.install "sin-code"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/OpenSIN-Code/SIN-Code/releases/download/v3.26.0/sin-code_3.26.0_linux_arm64.tar.gz"
      sha256 "931ae7b39cd4484ae368d3ffd8dcb11f84ff7555110f521478663d38d170b665"
      define_method(:install) do
        bin.install "sin-code"
      end
    end
  end

  test do
    system "#{bin}/sin-code", "--version"
  end
end
