# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SinCode < Formula
  desc "SIN-Code unified toolchain — 46+ analysis and manipulation tools in one binary"
  homepage "https://github.com/OpenSIN-Code/SIN-Code"
  version "3.24.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/OpenSIN-Code/SIN-Code/releases/download/v3.24.1/sin-code_3.24.1_darwin_amd64.tar.gz"
      sha256 "83172aa7bb8478364726b1051b9d0824435e687521d2bae22040bd0ffebf2a9a"

      define_method(:install) do
        bin.install "sin-code"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/OpenSIN-Code/SIN-Code/releases/download/v3.24.1/sin-code_3.24.1_darwin_arm64.tar.gz"
      sha256 "b519822e234569cb4872cc54dad6268b203cf0e65bbb1d9e6c4bb293c315e171"

      define_method(:install) do
        bin.install "sin-code"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/OpenSIN-Code/SIN-Code/releases/download/v3.24.1/sin-code_3.24.1_linux_amd64.tar.gz"
      sha256 "d16aeb3d422bbbac07cc8d4e5ee8964ff69d874dcb157230544a8dfa3191e9ef"
      define_method(:install) do
        bin.install "sin-code"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/OpenSIN-Code/SIN-Code/releases/download/v3.24.1/sin-code_3.24.1_linux_arm64.tar.gz"
      sha256 "fa1fafef213e2871236e1d90d6ea31fd130fa0ec842909acc72000c26fc27ff9"
      define_method(:install) do
        bin.install "sin-code"
      end
    end
  end

  test do
    system "#{bin}/sin-code", "--version"
  end
end
